In [2]:
import numpy as np
X_lam = np.random.randn(10, 1).reshape(5, 2)*10
X_lam

array([[ -6.52414801,  28.50508833],
       [ 15.93850848,  18.28576513],
       [-28.05454099,   7.03043552],
       [-13.62953392,   4.62486758],
       [ -0.92683877, -16.31722594]])

In [15]:
lam1 = lam[np.any(lam > 3, axis=1), :]
print(lam1)
lam2 = lam[:, np.any(lam > 3, axis=0)]
print(lam2)

[[ 7.53107146 -3.19930761]
 [ 7.89026284 -0.81958047]
 [ 3.92509563  3.38841976]]
[[ 7.53107146 -3.19930761]
 [ 7.89026284 -0.81958047]
 [ 3.92509563  3.38841976]]


In [18]:
(lam1 >= 0).astype(int) # 数値の要素に対してTrue or Falseで返す
# 全体をsum()して、条件に合うものの個数で条件付する

array([[1, 0],
       [1, 0],
       [1, 1]])

In [19]:
np.where(lam1 < 0, 0, lam1) # 数値の要素に対して、置換する

array([[7.53107146, 0.        ],
       [7.89026284, 0.        ],
       [3.92509563, 3.38841976]])