# week2 / assignment3

### 1. Inner product of vector

$$
    % "boldsymbol"で太字にしている
    \boldsymbol{A} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {c|cc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{ccc}
            -1 & 2 & 3\\
            4 & -5 & 6 \\
            7 & 8 & -9\\
        \end{array}\right] \quad
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
            % 横並びは&を挟む
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right] \quad
$$


行列の内積A*Bを手計算でときなさい。

$$
    \boldsymbol{A*B} =
        \left[\begin{array}{ccc}
            % 横並びは&を挟む
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

### 2. Calculate product of one dimensional array by for statement

In [5]:
"""

A*B : Caluculate the product of the matrix.
A:[3, 3]
B:[3, 3]

"""

"""

A*B :行列の積の1行目1列目を求める。
Aは、3×3行列です。
Bは、3×3行列です。

"""

import numpy as np

# define specified matrix A & B
A = np.array([[-1, 2, 3],
             [4, -5, 6],
             [7,  8, -9]])

B = np.array([[0, 2, 1],
             [0, 2, -8],
             [2,  9, -1]])

# Generate empty array
A_B_1 = np.array([])

# multiple matrix: each elements three times, each line three times
for num1 in range(3):
    # generate empty variable
    sum_line = 0
    for num2 in range(3):
        # add sum of elements
        sum_line += A[0][num2]*B[num2][num1]
    # append sum_line to output array
    A_B_1 = np.append(sum_line, A_B_1)
        
# Invert A_B_1
mul_matrix_A_B_1 = (A_B_1)[::-1]        
# Output
print(mul_matrix_A_B_1[0])

[  6.  29. -20.]


### 3.  How can we get all the elements?

In [2]:
"""

A*B : Caluculate the product of the matrix.
A:[3, 3]
B:[3, 3]

"""

"""

A*B :行列の積を求める。
Aは、3×3行列です。
Bは、3×3行列です。

"""
# array to store A*B
# A×Bを格納するアレイ
A_B_2 = np.array([])

"""
1, multiplication of elements
  → Total elements
  → Store total value in array
  → Update the value to 0
  → ...

2, Repeat 1 above three times with for statement and store one row of output vector in the array.

3. Repeat this for 3 lines and store them all in one array.

4, Finally, invert the array to form a 3 × 3 matrix.

"""

"""

1, 要素の掛け算
 → 要素を合計
 → アレイに合計値を格納
 → 要素合計の値を0に更新
 → …

2, 上記1をfor文で3回繰り返し、出力されるベクトルの1行分をアレイに格納する。

3, これを3行分繰り返し、すべて一つのアレイに格納する。

4, 最後に、アレイを反転させ、3×3の行列の形にする。

"""

for num0 in range(3):
    for num1 in range(3):
        sum_elements = 0
        for num2 in range(3):
            # add sum of elements
            sum_elements += A[num0][num2]*B[num2][num1]
        # append sum_line to output array
        A_B_2 = np.append(sum_elements, A_B_2)
        
# Invert and reshape A_B_1
mul_matirix_A_B = np.reshape((A_B_2)[::-1],(3, 3))
# Output
print(mul_matirix_A_B)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


### 4.Calculate inner product by np.dot

In [3]:
print(np.dot(A, B))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 5. What if you can not do inner product?

In [4]:
A = np.array([[-1, 2, 3],
             [4, -5, 6]])

B = np.array([[-9, 8, 7],
             [6, -5,4]])

# Generate transposed matrix
B_T = B.T

print(np.dot(A, B_T))

# 

[[ 46  -4]
 [-34  73]]
