# week2 / assignment3

### 1. Inner product of vector

$$
    % "boldsymbol"で太字にしている
    \boldsymbol{A} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {c|cc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{ccc}
            -1 & 2 & 3\\
            4 & -5 & 6 \\
            7 & 8 & -9\\
        \end{array}\right] \quad
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
            % 横並びは&を挟む
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right] \quad
$$


行列の内積A*Bを手計算でときなさい。


A・B = -1*0 + 2*2 + 3*1 
      + 4*0 + -5*2 + 6*-8
      +7*2 +8*9 +-9*-1
     
     =  -1 +   4 +   3 
       + 0  + -10 + -48
       + 14 +  72 +  9
     
###   A・B = 43


### 2. Calculate inner product of one dimensional array by for statement

In [91]:
import numpy as np

A = np.array([[-1, 2, 3],
             [4, -5, 6],
             [7,  8, -9]])

B = np.array([[0, 2, 1],
             [0, 2, -8],
             [2,  9, -1]])

A_B = np.array([])
array1 = np.array([])

for num1 in range(3):
        count = 0
        t = 0
        for num2 in range(3):
            t += A[count][num2]*B[num2][num1]
        array1 = np.append(t, array1)

print((array1)[::-1][0])


6.0


### 3.  How can we get all the elements?

In [92]:
A_B = np.array([])
array1 = np.array([])


for num0 in range(3):
    count = num0

    for num1 in range(3):
        t = 0
        for num2 in range(3):
            t += A[count][num2]*B[num2][num1]
        array1 = np.append(t, array1)

    
print(np.reshape((array1)[::-1], (3, 3)))
    


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


### 4.Calculate inner product by np.dot

In [93]:
print(np.dot(A, B))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 5. What if you can not do inner product?

In [94]:
A = np.array([[-1, 2, 3],
             [4, -5, 6]])

B = np.array([[-9, 8, 7],
             [6, -5,4]])

# Generate transposed matrix             
B_T = B.T
              
print(np.dot(A, B_T))

[[ 46  -4]
 [-34  73]]
